stages:
    - build
    - test
    - push

build_image:
    stage: build
    image: docker:19.03.1
    stage: build
    services:
      - docker:dind
    script:
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - DOCKER_BUILDKIT=1 docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
      - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
      #- #echo "ça build pas lol"
      #- #echo "Va cherche cette image pour build noob https://github.com/Zenika/nc-kubernetes-dev-tools/issues/19"

#    script:
#        - docker build . -t gitlab-runner:latest
#    artifacts:
#        paths:
#            - /var/lib/docker/gitlab-runner

